### ISSUE TITLE
Not working with django1.9.

### ISSUE THREAD

**Issue by Dharmik8478** [s-block/django-nested-inline#52]
I tried to run it with django1.9 and python3 and it gives me error 

> TypeError at /admin/user_management/college/add/
> 
> log_addition() missing 1 required positional argument: 'message'

In django1.9 it requires three arguments.

and while installing package it installs it inside site-packages as .zip file and so templates and js files are not rendering in project.

**Comment by Egregors** [comment]
The same issue

**Comment by Egregors** [comment]
@Dharmik8478, look at this. I did a little fix for this issue

**Comment by Dharmik8478** [comment]
Thanks it works fine @Egregors.

**Comment by davePlug** [comment]
@Egregors fix works fine.
+1 for pulling it in the next release.

**Comment by FFX01** [comment]
I also think this is a good commit as I have to do this fix manually every new project.

**Comment by OskarPersson** [comment]
Fixed in #55
