### ISSUE TITLE
Django 2.1 compatibility: has_add_permission() missing 1 required positional argument: 'obj'

### ISSUE THREAD

**Issue by MacLake** [s-block/django-nested-inline#93]
Afterupgrading I encountered a TypeEror in an admin page with django-nested-inline:
TypeError…:  has_add_permission() missing 1 required positional argument: 'obj'

After changing all  occurrences of `has_add_permission(request)` in `nested_inline/admin.py` to `has_add_permission(request, obj)`, it seems to work again.

But beware, I haven’t done any thorough testing.

**Comment by MacLake** [comment]
[My fork](https://github.com/MacLake/django-nested-inline) should and seems to be working with Dajngo 2.1. I have created a pull request.

**Comment by ZubAnt** [comment]
I also crashed with this problem

**Comment by Zagrebelin** [comment]
Will be fixed in django 2.1.6
